/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-hoverable-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

export {AnypointHoverableMixin};

declare namespace Anypoint {


  /**
   * **Note:** This is closed software and you can't use it in your projects unless
   * you are a Mulesoft employee working on internall project.
   *
   * Use `AnypointHoverableMixin` to implement an element that can be hovered.
   * The control will get a `hovered` attribute when it's hovered by the poiting devide.
   *
   * Be aware that mobile devices will not support hovering as desktop devices and behavior
   * may vary depending on platform. You should use this as little as possible.
   */
  function AnypointHoverableMixin<T extends new (...args: any[]) => {}>(base: T): T & AnypointHoverableMixinConstructor;

  interface AnypointHoverableMixinConstructor {
    new(...args: any[]): AnypointHoverableMixin;
  }

  interface AnypointHoverableMixin {

    /**
     * Set to `true` when the control is currently being hovered.
     */
    hovered: boolean|null|undefined;

    /**
     * Registers hover listeners
     */
    connectedCallback(): void;

    /**
     * Removes hover listeners
     */
    disconnectedCallback(): void;

    /**
     * Set's the `hovered` attribute to true when handled.
     */
    _hoverCallback(): void;

    /**
     * Updates `hovered` if the control is not hovered anymore.
     */
    _leaveCallback(): void;
  }
}

export {AnypointHoverableMixinConstructor};
